version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8819
      POSTGRES_DB: notificationTest
    networks:
      - notification
networks:
  notification: